build Docker image sdk-mvebu-cortexa9:
  stage: docker SDK
  needs: ["build test mvebu prpl security"]
  variables:
    DOCKER_DOCKERFILE_PATH: .gitlab/docker/sdk
    DOCKER_BUILD_EXTRA_ARGS: --build-arg DESIGNATED_BRANCH=$CI_DESIGNATED_BRANCH
  extends: .build Docker image
  before_script:
    - tar xf bin/targets/mvebu/cortexa9/openwrt-sdk-mvebu-cortexa9_gcc*Linux-x86_64.tar.xz --strip=1 -C .gitlab/docker/sdk

test Docker image sdk-mvebu-cortexa9:
  extends: .test Docker SDK image
  needs: ["build Docker image sdk-mvebu-cortexa9"]

deploy Docker image sdk-mvebu-cortexa9:
  stage: docker SDK deploy
  extends: .deploy Docker image
  needs: ["test Docker image sdk-mvebu-cortexa9"]


build Docker image sdk-x86-64:
  stage: docker SDK
  needs: ["build test x86_64 prpl security"]
  variables:
    DOCKER_DOCKERFILE_PATH: .gitlab/docker/sdk
    DOCKER_BUILD_EXTRA_ARGS: --build-arg DESIGNATED_BRANCH=$CI_DESIGNATED_BRANCH
  extends: .build Docker image
  before_script:
    - tar xf bin/targets/x86/64/openwrt-sdk-x86-64_gcc*.Linux-x86_64.tar.xz --strip=1 -C .gitlab/docker/sdk

test Docker image sdk-x86-64:
  extends: .test Docker SDK image
  needs: ["build Docker image sdk-x86-64"]

deploy Docker image sdk-x86-64:
  stage: docker SDK deploy
  extends: .deploy Docker image
  needs: ["test Docker image sdk-x86-64"]


build Docker image sdk-ipq807x-generic:
  stage: docker SDK
  needs: ["build test ipq807x prpl"]
  variables:
    DOCKER_DOCKERFILE_PATH: .gitlab/docker/sdk
    DOCKER_BUILD_EXTRA_ARGS: --build-arg DESIGNATED_BRANCH=$CI_DESIGNATED_BRANCH
  extends: .build Docker image
  before_script:
    - tar xf bin/targets/ipq807x/generic/openwrt-sdk-ipq807x-generic_gcc*.Linux-x86_64.tar.xz --strip=1 -C .gitlab/docker/sdk

test Docker image sdk-ipq807x-generic:
  extends: .test Docker SDK image
  needs: ["build Docker image sdk-ipq807x-generic"]

deploy Docker image sdk-ipq807x-generic:
  stage: docker SDK deploy
  extends: .deploy Docker image
  needs: ["test Docker image sdk-ipq807x-generic"]
